// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfqzbljiwkrksmjyfdiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmcXpibGppd2tya3NtanlmZGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzk5MDIsImV4cCI6MjA2NTc1NTkwMn0.7DpOfZVyLTSkuJ_ujXoFDdpz76cAKgEjoVyUwdp4jUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);